=== crinanis/Exams/4 sem/СТП/Ещё всякое/workWithXML/src/main/java/files/shema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"  xmlns:xs="http://www.w3.org/2001/XMLSchema" >

    <xs:element name="cards">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="card" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name"></xs:element>
                            <xs:element type="xs:byte" name="number"/>
                            <xs:element type="xs:float" name="sum"/>
                        </xs:sequence>
                        <xs:attribute name="id" use="optional" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== crinanis/Exams/4 sem/СТП/Ещё всякое/workWithXML/src/main/java/files/card.xml
<?xml version="1.0" encoding="utf-8" ?>
<cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="shema.xsd">

    <card id="c1">
        <name>Igor</name>
        <number>34</number>
        <sum>13</sum>
    </card>

    <card id="c2">
        <name>Diman</name>
        <number>123</number>
        <sum>20007</sum>
    </card>


</cards>
